# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlog',
            name='activity',
            field=models.CharField(choices=[('login_granted', 'Log In Granted'), ('login_denied', 'Log In Denied'), ('logout_granted', 'Log Out Granted'), ('logout_denied', 'Log Out Denied')], max_length=15),
        ),
    ]
