# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_auto_20170409_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='shirt_size',
        ),
        migrations.RemoveField(
            model_name='team',
            name='photo',
        ),
    ]
