# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import kri.apps.participant.models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0004_auto_20170409_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='manager',
            name='student_card',
            field=models.ImageField(default=None, null=True, upload_to=kri.apps.participant.models.manager_image_directory),
        ),
    ]
