# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0006_supporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(choices=[('core_member', 'Tim Inti'), ('mechanics', 'Mekanik'), ('adviser', 'Dosen Pembimbing'), ('supporter', 'Supporter'), ('pers', 'PERS')], max_length=11),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(choices=[('krai', 'KRAI'), ('krsbi_beroda', 'KRSBI Beroda'), ('krsti', 'KRSTI'), ('krpai', 'KRPAI'), ('pers', 'PERS')], max_length=12),
        ),
    ]
